# Generated by Django 3.0.6 on 2020-05-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trandingpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=30)),
                ('pub_date', models.DateField()),
                ('img', models.CharField(max_length=30)),
            ],
        ),
    ]
