# Generated by Django 3.0.6 on 2020-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200518_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trandingpost',
            name='desc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trandingpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
