# Generated by Django 3.0.6 on 2020-05-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200518_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trandingpost',
            name='desc',
        ),
        migrations.AlterField(
            model_name='trandingpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
