# Generated by Django 3.0.6 on 2020-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_trandingpost_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trandingpost',
            name='img',
            field=models.ImageField(default='', upload_to='news/images'),
        ),
    ]
