# Generated by Django 3.0.6 on 2020-05-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200518_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='trandingpost',
            name='details',
            field=models.CharField(default='-', max_length=500000),
        ),
    ]
