# Generated by Django 3.0.6 on 2020-05-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_trandingpost_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trandingpost',
            name='details',
            field=models.TextField(default='-', max_length=500000),
        ),
    ]
