# Generated by Django 3.0.6 on 2020-05-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200521_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='trandingpost',
            name='writer',
            field=models.CharField(default='Ashish', max_length=50),
        ),
    ]
