# Generated by Django 3.0.6 on 2020-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200530_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='trandingpost',
            name='imgname',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
