# Generated by Django 3.0.6 on 2020-06-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_trandingpost_imgname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trandingpost',
            name='imgname',
        ),
    ]
