# Generated by Django 3.0.6 on 2020-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_trandingpost_imgname'),
    ]

    operations = [
        migrations.AddField(
            model_name='trandingpost',
            name='imgname',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
