# Generated by Django 3.0.6 on 2020-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200603_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trandingpost',
            name='img',
            field=models.ImageField(default='', upload_to='media/news'),
        ),
    ]
