# Generated by Django 3.0.6 on 2020-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200603_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trandingpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trandingpost',
            name='catid',
        ),
        migrations.AlterField(
            model_name='trandingpost',
            name='img',
            field=models.ImageField(default='', upload_to='media/news'),
        ),
    ]
