# Generated by Django 3.0.6 on 2020-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200604_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trandingpost',
            name='img',
            field=models.ImageField(default='', upload_to='news'),
        ),
    ]
