# Generated by Django 3.0.6 on 2020-06-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat', models.CharField(max_length=20)),
                ('catname', models.CharField(max_length=20)),
                ('catid', models.IntegerField()),
            ],
        ),
    ]
